services:
  app:
    image: eclipse-temurin:25-jdk-alpine
    working_dir: /app
    env_file: ./.env
    environment:
      JAR_FILE: payment-gateway.jar
      LABS64_AUTH_AUTHZ_PDPADDRESS: cerbos:3593
      JAVA_TOOL_OPTIONS: >-
        -Duser.timezone=UTC
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      SPRING_PROFILES_ACTIVE: local
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
    ports:
      - "${APP_PORT:-8080}:8080"
      - "${DEBUG_PORT:-5005}:5005"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      cerbos:
        condition: service_healthy
    volumes:
      - type: bind
        source: ${HOST_PROJECT_DIR:-.}/target
        target: /app/target
        read_only: true
    command: ["sh", "-c", "java -jar /app/target/$$JAR_FILE"]
