APP_NAME := "payment-gateway"

# build application
build:
    mvn clean package -DskipTests

# build and run tests
test:
    mvn clean verify

# build docker image
docker: build
    docker build -t {{APP_NAME}}:latest .
    docker tag {{APP_NAME}}:latest localhost:5005/{{APP_NAME}}:latest
    docker push localhost:5005/{{APP_NAME}}:latest
    docker images | grep "{{APP_NAME}}"

# start local dev infrastructure (PostgreSQL + Redis + RabbitMQ)
infra-up:
    docker compose up -d
    docker ps -a

# stop local dev infrastructure
infra-down:
    docker compose down

# run application with local profile
run: build
    mvn spring-boot:run -Dspring-boot.run.profiles=local

# open documentation
docu:
    open "http://localhost:8080/swagger-ui.html"

# check maven dependencies/plugins/properties updates
check-updates:
    mvn versions:display-plugin-updates -Dmaven.version.ignore='(?i).*[.-]?(alpha|beta|RC|M)\d*'
    mvn versions:display-property-updates -Dmaven.version.ignore='(?i).*[.-]?(alpha|beta|RC|M)\d*'
    mvn versions:display-dependency-updates -DprocessDependencyManagement=false -Dmaven.version.ignore='(?i).*[.-]?(alpha|beta|RC|M)\d*'
    docker scout cves {{APP_NAME}}:latest
