apiVersion: v1
kind: ConfigMap
metadata:
  name: labs64-io-config
data:
  APP_DEFAULT_BROKER: "{{ .Values.app.defaultBroker }}"
  LABS64_DESTINATION: "{{ .Values.app.destination }}"
  KAFKA_BROKERS: "{{ .Values.kafka.brokers }}"
  KAFKA_SECURITY_PROTOCOL: "{{ .Values.kafka.securityProtocol }}"
  KAFKA_SASL_MECHANISM: "{{ .Values.kafka.saslMechanism }}"
  RABBITMQ_HOST: "{{ .Values.rabbit.host }}"
  RABBITMQ_PORT: "{{ .Values.rabbit.port }}"
  RABBITMQ_USERNAME: "{{ .Values.rabbit.username }}"
