apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-c-core
spec:
  replicas: {{ .Values.moduleC.replicas }}
  selector:
    matchLabels:
      app: module-c-core
  template:
    metadata:
      labels:
        app: module-c-core
    spec:
      containers:
        - name: module-c-core
          image: {{ .Values.moduleC.repository }}/{{ .Values.moduleC.image }}:{{ .Values.moduleC.tag }}
          envFrom:
            - configMapRef:
                name: labs64-io-config
            - secretRef:
                name: labs64-io-secret
          ports:
            - containerPort: 8080
