apiVersion: v1
kind: Secret
metadata:
  name: labs64-io-secret
type: Opaque
stringData:
  KAFKA_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="{{ .Values.kafka.username }}" password="{{ .Values.kafka.password }}";'
  RABBITMQ_PASSWORD: "{{ .Values.rabbit.password }}"
