repository: localhost:5005
moduleC:
  image: module-c-core
  tag: latest
  replicas: 1
moduleD:
  image: module-d-core
  tag: latest
  replicas: 1

app:
  defaultBroker: kafka
  destination: labs64-topic

kafka:
  brokers: kafka.default.svc.cluster.local:9092
  securityProtocol: SASL_PLAINTEXT
  saslMechanism: SCRAM-SHA-256
  username: labs64
  password: labs64pw

rabbit:
  host: rabbitmq.default.svc.cluster.local
  port: "5672"
  username: labs64
  password: labs64pw
